# Generated by Django 5.2.3 on 2025-07-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='dropoff_address',
            field=models.CharField(default='Not specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='package_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_address',
            field=models.CharField(default='Not specified', max_length=255),
            preserve_default=False,
        ),
    ]
