# Generated by Django 5.2.3 on 2025-07-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delivery_dropoff_address_delivery_package_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
