# Generated by Django 5.2.3 on 2025-07-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delivery_updated_at_alter_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('picked', 'Picked-Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
    ]
