# Generated by Django 5.2.3 on 2025-07-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
